module framework.smack_swing
{
    exports org.smack.swing.swingx.border;
//    exports org.smack.swing.swingx.plaf.synth;
    exports org.smack.swing.swingx.image;
    exports org.smack.swing.swingx.geom;
    exports org.smack.swing.swingx.tips;
    exports org.smack.swing.swingx.text;
    exports org.smack.swing.swingx.renderer;
    exports org.smack.swing.application;
//    exports org.smack.swing.swingx.auth;
//    exports org.smack.swing.swingx.hyperlink;
    exports org.smack.swing.swingx.sort;
    exports org.smack.swing.swingx.tree;
    exports org.smack.swing.swingx.decorator;
    exports org.smack.swing.swingx.graphics;
//    exports org.smack.swing.swingx.plaf;
//    exports org.smack.swing.smack.rendits;
//    exports org.smack.swing.swingx.plaf.basic;
    exports org.smack.swing.application.session;
    exports org.smack.swing.swingx.calendar;
    exports org.smack.swing.swingx.search;
    exports org.smack.swing.swingx;
    exports org.smack.swing.swingx.color;
//    exports org.smack.swing.swingx.plaf.metal;
    exports org.smack.swing.swingx.treetable;
//    exports org.smack.swing.swingx.util;
    exports org.smack.swing.application.util;
    exports org.smack.swing.swingx.icon;
    exports org.smack.swing.swingx.painter.effects;
//    exports org.smack.swing.swingx.autocomplete.workarounds;
    exports org.smack.swing.swingx.multisplitpane;
    exports org.smack.swing.swingx.combobox;
    exports org.smack.swing.beans;
//    exports org.smack.swing.swingx.plaf.linux;
    exports org.smack.swing.swingx.error;
//    exports org.smack.swing.swingx.multislider;
//    exports org.smack.swing.swingx.plaf.basic.core;
    exports org.smack.swing.swingx.table;
    exports org.smack.swing.swingx.prompt;
    exports org.smack.swing.application.converters;
    exports org.smack.swing.swingx.event;
//    exports org.smack.swing.swingx.plaf.windows;
//    exports org.smack.swing.smack;
//    exports org.smack.swing.swingx.rollover;
//    exports org.smack.swing.swingx.plaf.nimbus;
    exports org.smack.swing.swingx.painter;
//    exports org.smack.swing.swingx.plaf.misc;
    exports org.smack.swing.swingx.action;
//    exports org.smack.swing.swingx.plaf.macosx;
//    exports org.smack.swing.smack.actions;
//    exports org.smack.swing.swingx.autocomplete;

    requires transitive framework.smack;
    requires java.datatransfer;
    requires java.desktop;
    requires java.logging;
    requires java.naming;
    requires java.prefs;

    opens org.smack.swing.application to framework.smack;
}
